<new><ТЗ 15 сделано!>
v1aas/java-shareit pull request #3
Opened 2023-08-03 23:06 UTC by v1aas

2023-08-05 09:46 UTC, mikita95 requested changes
Все сделано хорошо. Оставил лишь несколько небольших замечаний

2023-08-05 09:46 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingFullDto postRequest(@RequestHeader("X-Sharer-User-Id") int userId,
Слишком общее название метода, лучше использовать более понятное, обозначающее суть метода

2023-08-05 09:46 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceDB.java
> +                PageRequest.of(0, 10)).toList();
Здесь захардкожены размеры страницы, нудно, пожалуй, использовать значения аргументов

2023-08-05 09:46 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceDB.java
> +                        BookingStatus.APPROVED, LocalDateTime.now(), PageRequest.of(from / size, size,
Эту дублирующуюся логику получения PageRequest можно вынести в какой-то утилитный класс, чтобы избежать дублирования

2023-08-05 09:46 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Data
Аннотацию Data не рекомендуется использовать над сущностями hibernate, так как она сгенерирует методы hashCode и toString, что может вызвать инициализацию lazy полей и циклические вызовы

2023-08-05 09:46 UTC, mikita95 commented on src/main/resources/schema.sql
> +    created timestamp
Эта колонка не может быть null

2023-08-06 09:36 UTC, v1aas commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingFullDto postRequest(@RequestHeader("X-Sharer-User-Id") int userId,
А ты точно про этот метод?) По-моему, в контроллере такой метод очень лаконично смотрится :)

2023-08-07 20:38 UTC, mikita95 approved these changes
Все сделано хорошо. Осталось еще замечание про имена методов, но можно это исправить и в дальнейшем.

2023-08-07 20:38 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingFullDto postRequest(@RequestHeader("X-Sharer-User-Id") int userId,
Точно :) В контроллере может быть несколько post методов, а также по имени метода должно быть понятно, что он делает, сейчас понятно лишь, что это post

2023-08-07 20:38 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>          return bookingService.postRequest(userId, bookingDto);
Также сервис вообще не должен знать про http и post, имя метода должно отражать его суть (createBooking, updateBooking, getBooking, и т.д)

2023-08-11 11:44 UTC, merged